## INIT

language: c
env:
  # - PYTHON_VERSION=2.6  NUMPY_VERSION=1.6.2 CYTHON="cython>=0.21"
  # - PYTHON_VERSION=2.7  NUMPY_VERSION=1.7.1 CYTHON="cython>=0.21"
  - PYTHON_VERSION=2.7  NUMPY_VERSION=1.8.2 CYTHON="cython>=0.21"


## INSTALL

before_install:
  # grab `conda` and bring it up to date
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x ./miniconda.sh;
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes --quiet conda
  - conda info -a

  # fix for the /dev/shm slink annoyance (bugs out `multiprocessing`)
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm

install:
  - conda create --yes --quiet -n py-${PYTHON_VERSION}_np-${NUMPY_VERSION} python=$PYTHON_VERSION numpy=${NUMPY_VERSION} pip scipy nose scikit-learn MDP pyyaml pytables $CYTHON
  - source activate py-${PYTHON_VERSION}_np-${NUMPY_VERSION}
  - python --version
  - python setup.py install

## SCRIPT

script:
  - nosetests

## EOF
