## INIT

language: python
python:
  - 2.6
  - 2.7
virtualenv:
  system_site_packages: true

## BRANCHES

branches:
  only:
    - master
    - 0.4-dev

## INSTALL

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install -qq cython
install:
  - echo "installing with pip"
  - pip install -r requirements.txt --use-mirrors
  - python setup.py build_ext
  - python setup.py install

## SCRIPT
before_script: ~
script:
  - nosetests
after_script: ~

## REPORTING

after_success:
  email: false
after_failure:
 email: true

## EOF
