## INIT

language: python
python:
#  - 2.6"
  - 2.7
#  - 3.3
#  - 3.4
notifications:


## INSTALL

before_install:
  - sudo apt-get update -qq
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy scikit-learn MDP pyyaml cython pytables
  - source activate test-environment
  - python setup.py build_ext install

## SCRIPT

script:
  - nosetests

## EOF
