## INIT

language: python
python:
  # don't do more than 5
  - 2.7
virtualenv:
  system_site_packages: true

## INSTALL

before_install:
  - ci/before_install.sh
install:
  - ci/install.sh

## SCRIPT

before_script:
  - echo
  - echo "======================================================================"
  - echo
script:
  - ci/script.sh
after_script:
  - echo
  - echo "======================================================================"
  - echo

## REPORTING

after_success:
  email: true
after_failure:
  email: true

## EOF
