language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-mdp python-sklearn
install:
  - python setup.py install
script: nosetests
notifications:
  email: false
after_success:
  email: false
