## INIT

language: python
python:
  - 2.6
  - 2.7
virtualenv:
  system_site_packages: true

## BRANCHES

branches:
  only:
    - master
    - 0.4-dev

## INSTALL

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install -qq python-dev python-numpy-dev
install:
  - pip install numpy>=1.6.1 --use-mirrors --quiet
  - pip install scipy>=0.9 --use-mirrors --quiet
  - pip install scikit-learn>=0.11 --use-mirrors --quiet
  - pip install MDP>=3.3 --use-mirrors --quiet
  - pip install cython>=0.15.1 --use-mirrors --quiet
  - python setup.py install

## SCRIPT

before_script:
  - echo
  - echo "======================================================================"
  - echo
script:
  - nosetests
after_script:
  - echo
  - echo "======================================================================"
  - echo

## REPORTING

after_success:
  email: false
after_failure:
 email: true

## EOF
